### ISSUE TITLE
Is this repo open for contribution?

### ISSUE THREAD

**Issue by silent-lad** [vuejs-in/companies-using-vuejs-in-India#1]

**Comment by sushant-j** [comment]
@swapagarwal  @znck - Just stumbled upon this repo. Would love to see this being actively used!

**Comment by swapagarwal** [comment]
Yes, it's open for contribution! We'd love to see more companies using Vue.js in India. 


---- On Thu, 11 Jul 2019 16:29:25 +0530 notifications@github.com wrote ----



@swapagarwal @znck - Just stumbled upon this repo. Would love to see this being actively used!
